apiVersion: apps/v1
kind: Deployment
metadata:
  name: checklist-messanger
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: checklist-messanger
  template:
    metadata:
      labels:
        app: checklist-messanger
    spec:
      containers:
      - name: checklist-messanger
        image: docker.io/bmzsombi/checklist-messanger:latest
        ports:
        - containerPort: 80
        env:
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: checklist-purchase-queue-default-user
              key: username
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: checklist-purchase-queue-default-user
              key: password
        - name: RABBITMQ_HOST
          value: "checklist-purchase-queue"