apiVersion: apps/v1
kind: Deployment
metadata:
  name: checklist-messanger
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: checklist-messanger
  template:
    metadata:
      labels:
        app: checklist-messanger
    spec:
      containers:
      - name: checklist-messanger
        image: docker.io/bmzsombi/checklist-messanger
        ports:
        - containerPort: 80
