apiVersion: v1
kind: Service
metadata:
  name: checklist-inventory-service
  namespace: checklist
  labels:
    app: checklist-inventory
spec:
  selector:
    app: checklist-inventory
  type: LoadBalancer
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 80