apiVersion: v1
kind: Service
metadata:
  name: checklist-inventory-service
  labels:
    app: checklist-inventory
spec:
  selector:
    app: checklist-inventory
  type: LoadBalancer
  LoadBalancerIP: 192.168.10.61
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 80