apiVersion: v1
kind: Service
metadata:
  name: checklist-shoppinglist-service
  labels:
    app: checklist-shoppinglist
spec:
  selector:
    app: checklist-shoppinglist
  type: LoadBalancer
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 80