apiVersion: apps/v1
kind: Deployment
metadata:
  name: checklist-shoppinglist
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: checklist-shoppinglist
  template:
    metadata:
      labels:
        app: checklist-shoppinglist
    spec:
      containers:
      - name: checklist-shoppinglist
        image: docker.io/bmzsombi/checklist-shoppinglist:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "checklist-database-rw"
        - name: DB_NAME
          value: "checklist_db"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: checklist-database-app
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: checklist-database-app
              key: password
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: checklist-queue-default-user
              key: username
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: checklist-queue-default-user
              key: password
        - name: RABBITMQ_HOST
          value: "checklist-queue"
