apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "checklist.fullname" . }}-inventory
  labels:
    app: {{ include "checklist.name" . }}-inventory
spec:
  replicas: {{ .Values.inventory.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ include "checklist.name" . }}-inventory
  template:
    metadata:
      labels:
        app: {{ include "checklist.name" . }}-inventory
    spec:
      containers:
      - name: inventory
        image: "{{ .Values.inventory.image.repository }}:{{ .Values.inventory.image.tag }}"
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "{{ .Values.global.database.host }}-rw"
        - name: DB_NAME
          value: {{ .Values.global.database.name | quote }}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.database.secretName }}
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.database.secretName }}
              key: password
        - name: RABBITMQ_HOST
          value: {{ .Values.global.rabbitmq.host | quote }}
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.rabbitmq.secretName }}
              key: username
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.rabbitmq.secretName }}
              key: password