apiVersion: v1
kind: Service
metadata:
  name: checklist-catalog-service
  labels:
    app: checklist-catalog
spec:
  selector:
    app: checklist-catalog
  type: LoadBalancer
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 80