apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cnpg/db.yaml
- rabbitmq/queue.yaml

- app/catalog/pvc.yaml
- app/catalog/catalog.yaml
- app/catalog/catalog-service.yaml

- app/inventory/inventory.yaml
- app/inventory/inventory-service.yaml

- app/shoppinglist/shoppinglist.yaml
- app/shoppinglist/shoppinglist-service.yaml

- app/messanger/messanger.yaml
- app/messanger/messanger-service.yaml

- app/frontend/admin/admin.yaml
- app/frontend/admin/admin-service.yaml