apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization







resources:
- cnpg/db.yaml
- rabbitmq/queue.yaml
- app/catalog/pvc.yaml
- app/catalog/catalog.yaml
- app/catalog/catalog-service.yaml
- app/inventory/inventory.yaml
- app/inventory/inventory-service.yaml
- app/shoppinglist/shoppinglist.yaml
- app/shoppinglist/shoppinglist-service.yaml
- app/messanger/messanger.yaml
- app/messanger/messanger-service.yaml
- app/frontend/admin/admin.yaml
- app/frontend/admin/admin-service.yaml
- app/frontend/responsible/responsible.yaml
- app/frontend/responsible/responsible-service.yaml
images:
- name: bmzsombi/checklist-admin
  newName: bmzsombi/checklist-admin
  newTag: 5bf3dde
- name: bmzsombi/checklist-catalog
  newName: bmzsombi/checklist-catalog
  newTag: 5bf3dde
- name: bmzsombi/checklist-inventory
  newName: bmzsombi/checklist-inventory
  newTag: 5bf3dde
- name: bmzsombi/checklist-messanger
  newName: bmzsombi/checklist-messanger
  newTag: 5bf3dde
- name: bmzsombi/checklist-responsible
  newName: bmzsombi/checklist-responsible
  newTag: 5bf3dde
- name: bmzsombi/checklist-shoppinglist
  newName: bmzsombi/checklist-shoppinglist
  newTag: 5bf3dde
