apiVersion: apps/v1
kind: Deployment
metadata:
  name: checklist-responsible
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: checklist-responsible
  template:
    metadata:
      labels:
        app: checklist-responsible
    spec:
      containers:
      - name: checklist-responsible
        image: docker.io/bmzsombi/checklist-responsible:latest
        ports:
        - containerPort: 80
