apiVersion: v1
kind: Service
metadata:
  name: checklist-responsible-service
  labels:
    app: checklist-responsible
spec:
  selector:
    app: checklist-responsible
  type: LoadBalancer
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 80