apiVersion: v1
kind: Service
metadata:
  name: checklist-admin-service
  labels:
    app: checklist-admin
spec:
  selector:
    app: checklist-admin
  type: LoadBalancer
  LoadBalancerIP: 192.168.10.67
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 80