name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Flutter Admin frontend
        uses: docker/build-push-action@v5
        with:
          context: ./src/frontend/admin/
          push: true
          tags: bmzsombi/checklist-admin:${{ steps.vars.outputs.sha_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Flutter Responsible frontend
        uses: docker/build-push-action@v5
        with:
          context: ./src/frontend/responsible/
          push: true
          tags: bmzsombi/checklist-responsible:${{ steps.vars.outputs.sha_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push messanger
        uses: docker/build-push-action@v5
        with:
          context: ./src/messanger
          push: true
          tags: bmzsombi/checklist-messanger:${{ steps.vars.outputs.sha_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push catalog
        uses: docker/build-push-action@v5
        with:
          context: ./src/db/catalog/
          push: true
          tags: bmzsombi/checklist-catalog:${{ steps.vars.outputs.sha_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build and push inventory
        uses: docker/build-push-action@v5
        with:
          context: ./src/db/inventory/
          push: true
          tags: bmzsombi/checklist-inventory:${{ steps.vars.outputs.sha_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push shoppinglist
        uses: docker/build-push-action@v5
        with:
          context: ./src/db/shoppinglist/
          push: true
          tags: bmzsombi/checklist-shoppinglist:${{ steps.vars.outputs.sha_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Kustomization
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          
          cd kubernetes

          ../kustomize edit set image bmzsombi/checklist-admin=bmzsombi/checklist-admin:${{ steps.vars.outputs.sha_short }}
          ../kustomize edit set image bmzsombi/checklist-responsible=bmzsombi/checklist-responsible:${{ steps.vars.outputs.sha_short }}
          ../kustomize edit set image bmzsombi/checklist-messanger=bmzsombi/checklist-messanger:${{ steps.vars.outputs.sha_short }}
          ../kustomize edit set image bmzsombi/checklist-catalog=bmzsombi/checklist-catalog:${{ steps.vars.outputs.sha_short }}
          ../kustomize edit set image bmzsombi/checklist-inventory=bmzsombi/checklist-inventory:${{ steps.vars.outputs.sha_short }}
          ../kustomize edit set image bmzsombi/checklist-shoppinglist=bmzsombi/checklist-shoppinglist:${{ steps.vars.outputs.sha_short }}

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add kubernetes/kustomization.yaml
          git commit -m "chore: update images in kustomization.yaml [skip ci]"
          git push
      
